multicast-menu/multicast/apps/add/urls.py
from django.urls import path

from . import views


app_name = "add"

urlpatterns = [
    path("", views.index, name="index"),
    path("manual/", views.add_manual, name="add_manual"),
    path("upload/", views.add_upload, name="add_upload"),
]

multicast-menu/multicast/apps/manage/urls.py
from django.urls import path

from . import views

app_name = "manage"

urlpatterns = [
    path("", views.index, name="index"),
    path("edit/<int:stream_id>", views.edit, name="edit"),
    path("remove/<int:stream_id>", views.remove, name="remove"),
    path("retry_verification/<int:stream_id>", views.retry_verification, name="retry_verification"),
]

multicast-menu/multicast/apps/view/urls.py
from django.urls import path

from . import views

app_name = "view"

urlpatterns = [
    path('media/tunnel-files/<path:path>', views.serve_media_file, name='serve_media_file'),
    path("register/", views.register, name="register"),
    path("", views.index, name="index"),
    path("trending/", views.trending_index, name="trending_index"),
    path("editors_choice/", views.editors_choice_index, name="editors_choice_index"),
    path("liked/", views.liked_index, name="liked_index"),
    path("detail/<int:stream_id>/", views.detail, name="detail"),
    path("detail/open/<int:stream_id>/", views.open_file, name="open"),
    path("detail/watch/<int:stream_id>/", views.watch, name="watch"),
    path("detail/report/<int:stream_id>/", views.report, name="report"),
    path("description/upvote/<int:description_id>/", views.upvote_description, name="upvote_description"),
    path("description/downvote/<int:description_id>/", views.downvote_description, name="downvote_description"),
    path("description/submit/<int:stream_id>/", views.submit_description, name="submit_description"),
    path("broken/", views.broken_index, name="broken_index"),
    path("broken/detail/<int:stream_id>/", views.broken_detail, name="broken_detail"),
    path("broken/clear/<int:stream_id>/", views.broken_clear, name="broken_clear"),
    path("detail/set_editors_choice/<int:stream_id>/", views.set_editors_choice, name="set_editors_choice"),
    path("detail/like_stream/<int:stream_id>/", views.like_stream, name="like_stream"),
    path("detail/remove_like_from_stream/<int:stream_id>/", views.remove_like_from_stream, name="remove_like_from_stream"),
    path('check_stream_status/<int:stream_id>/', views.check_stream_status, name='check_stream_status'),
]

multicast-menu/multicast/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import include, path

from multicast.apps.view.forms import CustomLoginForm

urlpatterns = ([
    path("login/", LoginView.as_view(authentication_form=CustomLoginForm), name="login"),
    path("", include("django.contrib.auth.urls")),
    path("", include("multicast.apps.view.urls", namespace="view")),
    path("add/", include("multicast.apps.add.urls", namespace="add")),
    path("admin/", admin.site.urls),
    path("api/", include("multicast.apps.add.api_urls", namespace="api")),
    path("manage/", include("multicast.apps.manage.urls", namespace="manage")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

multicast-menu/multicast/apps/add/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.shortcuts import redirect, render
from django.urls import reverse

from ...utils import create_random_string
from .forms import ManualSubmissionForm, UploadSubmissionForm
from .models import ManualSubmission, UploadSubmission
from .tasks import submit_file_to_translator, verify_manual_report
from multicast.apps.view.tasks import create_preview_for_stream
import os

# Index page for add where an authenticated user can select how they would like to add a stream
@login_required
def index(request):
    return render(request, "add/index.html")


# Allows an authenticated user to manually report a stream
@login_required
def add_manual(request):
    RELAY_LIST = ((0, "amt-relay.m2icast.net"), (1, "amt-relay.geant.org"), (2, "Other (please specify)"))

    form = ManualSubmissionForm(data_list=RELAY_LIST)

    if request.method == "POST":
        form = ManualSubmissionForm(request.POST, data_list=RELAY_LIST)
        if form.is_valid():
            stream = form.save()
            stream.owner = request.user
            stream.active = False
            stream.collection_method = "02"
            stream.amt_relay = RELAY_LIST[int(form.cleaned_data["amt_relay"])][1]
            stream.save()

            if int(form.cleaned_data["amt_relay"]) == 2:
                stream.amt_relay = form.cleaned_data["amt_relay_other"]
                stream.save()

            report = ManualSubmission.objects.create(
                stream=stream,
                active=False,
            )
            verify_manual_report(stream.id)
            report.save()

            # Create the preview for the stream
            # create_preview_for_stream(stream.id)

            return redirect(reverse("manage:index"))
    
    return render(request, "add/add_manual.html", context={"form": form})


# Allows an authenticated user to upload a file to be streamed
@login_required
def add_upload(request):
    form = UploadSubmissionForm()

    if request.method == "POST":
        form = UploadSubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            stream = form.save()
            stream.owner = request.user
            stream.active = False
            stream.collection_method = "03"
            stream.save()

            file_name = create_random_string(40) + os.path.splitext(form.cleaned_data["file_to_stream"].name)[1]
            file_path = os.path.join('uploads', file_name)
            file_url = default_storage.save(file_path, form.cleaned_data["file_to_stream"])

            upload = UploadSubmission.objects.create(
                stream=stream,
                active=False,
                uploaded_file=file_url,
                access_code=create_random_string(40),
            )
            upload.celery_id = submit_file_to_translator.delay(stream.id).id
            upload.save()

            return redirect(reverse("manage:index"))

    return render(request, "add/add_upload.html", context={"form": form})

multicast-menu/multicast/apps/view/views.py
import time

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.http import FileResponse
from wsgiref.util import FileWrapper
from django.shortcuts import get_object_or_404, render
from django.views.decorators.cache import never_cache
from django.db.models import F
from django.db import connection
from datetime import datetime

from redis import Redis
from .models import Stream, Tunnel
from .tasks import open_tunnel, start_ffmpeg
import time
import logging
import glob
from datetime import datetime

from .forms import DescriptionForm, CustomUserCreationForm
from .models import Category, Description, Stream, TrendingStream, Tunnel

from ...settings import TRENDING_STREAM_MAX_VISIBLE_SIZE, MEDIA_ROOT, CELERY_BROKER_URL
from .tasks import open_tunnel, start_ffmpeg

import os

logger = logging.getLogger(__name__)


def is_ajax(request):
    """
    Calling request.is_ajax() results in the following error:
        AttributeError: 'WSGIRequest' object has no attribute 'is_ajax'
    This function reproduces the functionality of request.is_ajax() without the error.

    References:
        AttributeError: 'WSGIRequest' object has no attribute 'is_ajax',
        https://stackoverflow.com/questions/70419441/attributeerror-wsgirequest-object-has-no-attribute-is-ajax

    :param request:
    :return:
    """
    return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


# Allow a user to create an account
def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("login"))
    else:
        form = CustomUserCreationForm()

    return render(request, "registration/register.html", context={"form": form})


# Home page listing all active streamseported_index
def index(request):
    # Get all categories from the database
    categories = Category.objects.all()
    # Get the active category from the request, defaulting to empty string if there is no category
    str_active_category = request.GET.get("category", "")
    # Get all active streams from the database
    stream_list = Stream.objects.filter(active=True).order_by("-created_at")

    if str_active_category:
        # Get a query set with the active category from the database
        active_category_set = categories.filter(slug=str_active_category)
        # Get the distinct streams with categories in the active category set
        stream_list = stream_list.filter(categories__in=active_category_set).distinct()

    # Get the search query from the request
    str_query = request.GET.get("query", "")
    if str_query:
        stream_list = stream_list.filter(description__icontains=str_query)

    # Show 24 streams per page
    paginator = Paginator(stream_list, 24)
    # Get the requested page number
    page_number = request.GET.get("page")
    # Get the page from the request
    page_obj = paginator.get_page(page_number)

    context = {
        "categories": categories,
        "active_category": str_active_category,
        "page_obj": page_obj,
        "query": str_query,
        "TRENDING_STREAM_MAX_VISIBLE_SIZE": TRENDING_STREAM_MAX_VISIBLE_SIZE,
    }
    return render(request, "view/index.html", context)


def trending_index(request):
    stream_list = []
    for trending_stream in TrendingStream.objects.all():
        if trending_stream.stream.active:
            stream_list.append(trending_stream.stream)
    context = {
        "stream_list": stream_list[0:TRENDING_STREAM_MAX_VISIBLE_SIZE],
        "TRENDING_STREAM_MAX_VISIBLE_SIZE": TRENDING_STREAM_MAX_VISIBLE_SIZE,
    }
    return render(request, "view/trending_index.html", context=context)


def editors_choice_index(request):
    context = {
        "stream_list": Stream.objects.filter(editors_choice=True, active=True),
        "TRENDING_STREAM_MAX_VISIBLE_SIZE": TRENDING_STREAM_MAX_VISIBLE_SIZE,
    }
    return render(request, "view/editors_choice_index.html", context=context)


@login_required()
def liked_index(request):
    if request.user.is_authenticated:
        # Get all active and liked streams
        # Reversed in order to show the most recently liked streams first
        liked_streams = reversed(request.user.liked_streams.filter(active=True))
        context = {
            "stream_list": liked_streams,
            "TRENDING_STREAM_MAX_VISIBLE_SIZE": TRENDING_STREAM_MAX_VISIBLE_SIZE,
        }
        return render(request, "view/liked_index.html", context=context)
    raise PermissionDenied


# Detail page for a specific stream
def detail(request, stream_id):
    stream = get_object_or_404(Stream, id=stream_id)

    context = {
        "stream": stream,
        "descriptions": Description.objects.filter(stream=stream).order_by("-votes")[
            :3
        ],
        "description_form": (
            DescriptionForm() if request.user.is_authenticated else None
        ),
        "num_likes": stream.likes.count(),
        "stream_is_liked_by_user": request.user.is_authenticated
        and request.user in stream.likes.all(),
        "TRENDING_STREAM_MAX_VISIBLE_SIZE": TRENDING_STREAM_MAX_VISIBLE_SIZE,
    }

    return render(request, "view/detail.html", context=context)


def serve_media_file(request, path):
    file_path = os.path.join(MEDIA_ROOT, "tunnel-files", path)
    print(f"Requested file path: {file_path}")

    try:
        if os.path.exists(file_path):
            print(f"File exists: {file_path}")
            with open(file_path, "rb") as file_handle:
                content_type = (
                    "application/vnd.apple.mpegurl"
                    if path.endswith(".m3u8")
                    else "video/mp2t"
                )
                response = HttpResponse(
                    FileWrapper(file_handle), content_type=content_type
                )
                response["Content-Disposition"] = (
                    f'inline; filename="{os.path.basename(file_path)}"'
                )
                response["Cache-Control"] = (
                    "no-store, no-cache, must-revalidate, max-age=0"
                )
                response["Pragma"] = "no-cache"
                response["Expires"] = "Thu, 01 Jan 1970 00:00:00 GMT"
                print(f"Serving file: {file_path}")
                return response
        else:
            print(f"File does not exist at the given path: {file_path}")
            raise Http404("File not found")
    except Exception as e:
        print(f"Error serving file: {str(e)}")
        raise Http404("File not found")


@never_cache
def watch(request, stream_id):
    # Clear up resources
    connection.close()
    redis = Redis.from_url(CELERY_BROKER_URL)
    
    # Attempt to remove idle clients
    try:
        all_clients = redis.client_list()
        for client in all_clients:
            if client.get('flags', '') == 'N' and int(client.get('idle', 0)) > 300:  # 5 minutes idle
                redis.client_kill(addr=client['addr'])
    except Exception as e:
        print(f"Error cleaning up Redis clients: {e}")

    stream = get_object_or_404(Stream, id=stream_id)
    tunnel, created = Tunnel.objects.get_or_create(stream=stream)

    if not tunnel.amt_gateway_up:    # Debug logging
        open_tunnel.delay(tunnel.id)
    
    if not tunnel.ffmpeg_up:
        start_ffmpeg.delay(tunnel.id)

    Tunnel.objects.filter(id=tunnel.id).update(active_viewer_count=F('active_viewer_count') + 1)

    context = {
        "stream_id": stream_id,
        "status_check_url": reverse("view:check_stream_status", args=[stream_id]),
    }

    response = render(request, "view/watch.html", context=context)
    response['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response['Pragma'] = 'no-cache'
    response['Expires'] = 'Thu, 01 Jan 1970 00:00:00 GMT'

    return response


@never_cache
def check_stream_status(request, stream_id):
    stream = get_object_or_404(Stream, id=stream_id)
    tunnel = get_object_or_404(Tunnel, stream=stream)

    output_file = os.path.join(MEDIA_ROOT, "tunnel-files", tunnel.get_filename())
    print(f"Checking status for stream {stream_id}. Output file: {output_file}")

    if os.path.exists(output_file):
        print(f"M3U8 file exists: {output_file}")
        ts_files = glob.glob(f"{output_file}_*.ts")
        print(f"Found {len(ts_files)} TS files")
        if ts_files:
            watch_file = f"/media/tunnel-files/{tunnel.get_filename()}"
            print(f"Stream ready. Watch file URL: {watch_file}")
            return JsonResponse({
                "status": "ready",
                "watch_file": watch_file,
            })
    
    print("Stream not ready yet")
    return JsonResponse({"status": "not_ready"})


# Download a .m3u file for the user to open in VLC
def open_file(request, stream_id):
    stream = get_object_or_404(Stream, id=stream_id)

    response = HttpResponse()
    response["Content-Disposition"] = 'attachment; filename="playlist.m3u"'
    response.write("amt://{}@{}".format(stream.source, stream.group))
    if stream.udp_port:
        response.write(":{}".format(stream.udp_port))

    return response


# Allow users to report broken streams
def report(request, stream_id):
    stream = get_object_or_404(Stream, id=stream_id)

    if is_ajax(request):
        stream.report()
        return JsonResponse(dict())
    else:
        raise Http404


# Allow users to upvote a description
def upvote_description(request, description_id):
    description = get_object_or_404(Description, id=description_id)

    if is_ajax(request):
        description.upvote()
        return JsonResponse(dict())

multicast-menu/multicast/templates/view/broken_detail.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/view.css' %}">
    <script>
        function clear_reports(stream_id) {
            $.ajax({
                type: "GET",
                url: "{% url 'view:broken_clear' 1234 %}".replace(/1234/, stream_id),
                success: function () {
                    alert("Any reports for this stream have been cleared and it will again appear to users.");
                },
            });
        }
    </script>
{% endblock %}

{% block main %}
    <div style="max-width: 880px; margin: auto;">
        <!-- Preview image -->
        <div>
            {% if stream.preview %}
                <img class="responsive-image detail-padding" src={{ stream.preview.url }}>
            {% endif %}
        </div>
        <!-- Title, organization, owner...-->
        <div class="detail-margin">
            <h1 style="font-size: 22px; font-weight: bold;">{{ stream.get_description }}</h1>
            <h2 style="font-size: 14px;">Organization: {{ stream.source_name }}</h2>
            <h2 style="font-size: 14px;">Owner: {{ stream.owner.username }}</h2>
            <h2 style="font-size: 14px;">Source: {{ stream.source }}</h2>
            <h2 style="font-size: 14px;">Group: {{ stream.group }}</h2>
            {% if stream.udp_port %}
                <h2 style="font-size: 14px;">UDP Port: {{ stream.udp_port }}</h2>
            {% endif %}
            {% if stream.amt_relay %}
                <h2 style="font-size: 14px;">AMT Relay: {{ stream.amt_relay }}</h2>
            {% endif %}
        </div>
        <!-- Open in VLC -->
        <div class="detail-margin">
            <a href="{% url 'view:open' stream.id %}">
                <button type="button" class="btn detail-button detail-padding">
                    <svg xmlns="http://www.w3.org/2000/svg" style="width: 32px; height: 32px; padding-bottom: 2px;" fill="currentColor" class="bi bi-play-circle-fill" viewBox="0 0 16 16">
                      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.79 5.093A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814l-3.5-2.5z"/>
                    </svg>
                    Open in VLC
                </button>
            </a>
        </div>
        <div class="text-box">
            <h6>This stream was collected through: {{ stream.collection_method }}</h6>
            <h6>This stream was last collected at {{ stream.get_time_last_found }} UTC.</h6>
            <h6>This stream has been reported as broken {{ stream.report_count }} times.</h6>
        </div>
        <!-- Mark Active -->
        <div class="detail-margin">
            <a><button type="button" class="btn detail-button detail-padding" onclick="clear_reports('{{ stream.id }}')">
                <svg xmlns="http://www.w3.org/2000/svg" style="width: 32px; height: 32px; padding-bottom: 2px;" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                    <path d="M5 3a5 5 0 0 0 0 10h6a5 5 0 0 0 0-10H5zm6 9a4 4 0 1 1 0-8 4 4 0 0 1 0 8z"/>
                </svg>
                Mark Active
            </button></a>
        </div>
        <!-- Delete Stream -->
        <div class="detail-margin">
            <form method="post">
                {% csrf_token %}
                <a><button type="submit" class="btn detail-button detail-padding">
                    <svg xmlns="http://www.w3.org/2000/svg" style="width: 32px; height: 32px; padding-bottom: 2px;" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                      <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                    </svg>
                    Delete Stream
                </button></a>
            </form>
        </div>
    </div>
{% endblock %}

multicast-menu/multicast/templates/view/broken_index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block main %}
    <div class="center-div">
        <h2>Broken Streams</h2>
        <h6>The following streams have been marked inactive and are no longer shown to users. You can click each one to view its details and take appropriate action.</h6>
    </div>
    <div class="stream-cards">
        {% for stream in stream_list %}
            <article>
                <figure class="stream-card-header">
                    <a href="{% url 'view:broken_detail' stream.id %}"></a>
                    {% if stream.thumbnail %}
                        <img src={{ stream.thumbnail.url }} alt="" class="thumbnail">
                    {% else %}
                        <img src="{% static 'img/svg/image-fill.svg' %}" class="fallback-thumbnail">
                    {% endif %}
                </figure>
                <div class="stream-card-body">
                    <a href="{% url 'view:broken_detail' stream.id %}" class="invisible-a">
                        <strong style="display: block">
                            {{ stream.get_description }}
                        </strong>
                    </a>
                    {{ stream.source_name }}
                </div>
            </article>
        {% endfor %}
    </div>
{% endblock %}

multicast-menu/multicast/templates/view/editors_choice_index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block main %}
    <div class="center-div">
        <h2>Editors' Choice Streams</h2>
        <h6>Editors' Choice is a curated collection of streams that highlights some of the very best streams available on MulticastMenu.</h6>
    </div>
    <div class="stream-cards">
        {% for stream in stream_list %}
            {% include "components/stream_card.html" %}
        {% endfor %}
    </div>
{% endblock %}

multicast-menu/multicast/templates/view/index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/view.css' %}">

    <script>
        /**
         * Add an event listener to the Document.
         * When the content is loaded, check if the horizontal scroll position of the div with all categories
         * (the div with the id categories_chooser) is saved in the sessionStorage.
         * If the value is saved scroll the divider to this position and clear the value from the storage.
         * That way the user will have the same categories in sight after a click on one of them.
         */
        document.addEventListener("DOMContentLoaded", function (event) {
            var scrollpos = sessionStorage.getItem('categories_scrollpos');
            if (scrollpos) {
                var categoriesChooser = document.getElementById("categories_chooser");
                if(categoriesChooser) {
                    categoriesChooser.scrollTo(scrollpos, 0);
                }
                sessionStorage.removeItem('categories_scrollpos');
            }
        });

        /**
         * Add an event listener to the window.
         * The moment before the content is unloaded get the position of the div with all categories
         * (the div with the id categories_chooser) and save it to the sessionStorage in order to
         * reuse it when the document is loaded again.
         */
        window.addEventListener("beforeunload", function (e) {
            var categoriesChooser = document.getElementById("categories_chooser");
            if(categoriesChooser) {
                sessionStorage.setItem('categories_scrollpos', categoriesChooser.scrollLeft);
            }
        });
    </script>
{% endblock %}

{% block main %}
    <!-- Categories -->
    <div id="categories_chooser" class="frame" style="overflow: auto; white-space: nowrap; padding: 18px; border: 1px solid rgba(0,0,0,0.1); font-size: 1rem;">
        <span style="font-weight: bold;">Categories:</span>
        <a href="{% url 'view:index' %}" style="color: inherit; text-decoration: none;">
            <span class="{% if not active_category %} category-tag-selected {% else %} category-tag {% endif %}" style="padding: 0.5rem 0.5rem 0.5rem 0.7rem; margin: 0.3rem;">
                All
            </span>
        </a>
        {% for category in categories %}
            <a href="{% url 'view:index' %}?category={{ category.slug }}" style="color: inherit; text-decoration: none;">
                <span class="{% if category.slug == active_category %} category-tag-selected {% else %} category-tag {% endif %}" style="padding: 0.5rem 0.5rem 0.5rem 0.7rem; margin: 0.3rem;">
                    {{ category.name }}
                </span>
            </a>
        {% endfor %}
    </div>
    <!-- Main content -->
    <div class="wrapper">
        <!-- Mian content header -->
        <div class="center-div" style="padding: 10px 0;">
            {% if query %}
                {% if page_obj.paginator.count == 0 %}
                    <h5>No streams found for your search term "{{ query }}".</h5>
                {% elif page_obj.paginator.count == 1 %}
                    <h5>1 stream found for search term "{{ query }}".</h5>
                {% else %}
                    <h5>{{ page_obj.paginator.count }} streams found for search term "{{ query }}" (showing {{ page_obj.start_index }} to {{ page_obj.end_index }}).</h5>
                {% endif %}
            {% elif active_category %}
                {% if page_obj.paginator.count == 0 %}
                    <h5>No streams found in the selected category.</h5>
                {% elif page_obj.paginator.count == 1 %}
                    <h5>1 stream found in the selected category.</h5>
                {% else %}
                    <h5>{{ page_obj.paginator.count }} streams found in the selected category (showing {{ page_obj.start_index }} to {{ page_obj.end_index }}).</h5>
                {% endif %}
            {% else %}
                {% if page_obj.paginator.count == 0 %}
                    <h5>No streams are currently available on the platform.</h5>
                {% elif page_obj.paginator.count == 1 %}
                    <h5>1 available stream is listed below.</h5>
                {% else %}
                    <h5>{{ page_obj.paginator.count }} available streams are listed below (showing {{ page_obj.start_index }} to {{ page_obj.end_index }}).</h5>
                {% endif %}
            {% endif %}
            {% if page_obj.paginator.count > 0 %}
                <h6>Make sure you have <a target="_blank" href="https://nightlies.videolan.org/">VLC 4.0 or later</a> installed.</h6>
            {% endif %}
        </div>
        <!-- Stream cards -->
        <div class="stream-cards">
            {% for stream in page_obj %}
                {% include "components/stream_card.html" %}
            {% endfor %}
        </div>
        <!-- Pages -->
        {% if page_obj.paginator.count > 0 %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        {% if query %}
                            <a class="page-link" href="?query={{ query }}&page=1">First</a>
                        {% elif active_category %}
                            <a class="page-link" href="?category={{ active_category }}&page=1">First</a>
                        {% else %}
                            <a class="page-link" href="?page=1">First</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        {% if query %}
                            <a class="page-link" href="?query={{ query }}&page={{ page_obj.previous_page_number }}">Previous</a>
                        {% elif active_category %}
                            <a class="page-link" href="?category={{ active_category }}&page={{ page_obj.previous_page_number }}">Previous</a>
                        {% else %}
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        {% endif %}
                    </li>
                {% endif %}
                <li class="page-item active">
                  <a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        {% if query %}
                            <a class="page-link" href="?query={{ query }}&page={{ page_obj.next_page_number }}">Next</a>
                        {% elif active_category %}
                            <a class="page-link" href="?category={{ active_category }}&page={{ page_obj.next_page_number }}">Next</a>
                        {% else %}
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        {% if query %}
                            <a class="page-link" href="?query={{ query }}&page={{ page_obj.paginator.num_pages }}">Last</a>
                        {% elif active_category %}
                            <a class="page-link" href="?category={{ active_category }}&page={{ page_obj.paginator.num_pages }}">Last</a>
                        {% else %}
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                        {% endif %}
                    </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

multicast-menu/multicast/templates/view/liked_index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block main %}
    <div class="center-div">
        <h2>Liked Streams</h2>
        <h6>The following list contains every streams on MulticastMenu, which you have liked.</h6>
    </div>
    <div class="stream-cards">
        {% for stream in stream_list %}
            {% include "components/stream_card.html" %}
        {% endfor %}
    </div>
{% endblock %}

multicast-menu/multicast/templates/view/trending_index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block main %}
    <div class="center-div">
        <h2>Trending Streams</h2>
        <h6>The following streams are the most popular and currently trending streams on MulticastMenu.</h6>
    </div>
    <div class="stream-cards">
        {% for stream in stream_list %}
            {% include "components/stream_card.html" %}
        {% endfor %}
    </div>
{% endblock %}